//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlagMaker.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlagMaker.Localization.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files.
        /// </summary>
        public static string AllFiles {
            get {
                return ResourceManager.GetString("AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone.
        /// </summary>
        public static string Clone {
            get {
                return ResourceManager.GetString("Clone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t load presets. Check for a Presets folder in the application directory..
        /// </summary>
        public static string CouldNotLoadPresetsError {
            get {
                return ResourceManager.GetString("CouldNotLoadPresetsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t open the file. Check your syntax and try again. Error at line: &quot;{0}&quot;.
        /// </summary>
        public static string CouldNotOpenError {
            get {
                return ResourceManager.GetString("CouldNotOpenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t open the file. Check your syntax and try again..
        /// </summary>
        public static string CouldNotOpenFileError {
            get {
                return ResourceManager.GetString("CouldNotOpenFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal count.
        /// </summary>
        public static string CountX {
            get {
                return ResourceManager.GetString("CountX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical count.
        /// </summary>
        public static string CountY {
            get {
                return ResourceManager.GetString("CountY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division.
        /// </summary>
        public static string Division {
            get {
                return ResourceManager.GetString("Division", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bends backward.
        /// </summary>
        public static string DivisionBendsBackward {
            get {
                return ResourceManager.GetString("DivisionBendsBackward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bends both.
        /// </summary>
        public static string DivisionBendsBoth {
            get {
                return ResourceManager.GetString("DivisionBendsBoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bends forward.
        /// </summary>
        public static string DivisionBendsForward {
            get {
                return ResourceManager.GetString("DivisionBendsForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blank.
        /// </summary>
        public static string DivisionBlank {
            get {
                return ResourceManager.GetString("DivisionBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fesses.
        /// </summary>
        public static string DivisionFesses {
            get {
                return ResourceManager.GetString("DivisionFesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid.
        /// </summary>
        public static string DivisionGrid {
            get {
                return ResourceManager.GetString("DivisionGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal halves.
        /// </summary>
        public static string DivisionHorizontalHalves {
            get {
                return ResourceManager.GetString("DivisionHorizontalHalves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pales.
        /// </summary>
        public static string DivisionPales {
            get {
                return ResourceManager.GetString("DivisionPales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presets.
        /// </summary>
        public static string DivisionPresets {
            get {
                return ResourceManager.GetString("DivisionPresets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quartered.
        /// </summary>
        public static string DivisionQuartered {
            get {
                return ResourceManager.GetString("DivisionQuartered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stripes.
        /// </summary>
        public static string DivisionStripes {
            get {
                return ResourceManager.GetString("DivisionStripes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical halves.
        /// </summary>
        public static string DivisionVerticalHalves {
            get {
                return ResourceManager.GetString("DivisionVerticalHalves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emblems.
        /// </summary>
        public static string Emblems {
            get {
                return ResourceManager.GetString("Emblems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error at line:.
        /// </summary>
        public static string ErrorAtLine {
            get {
                return ResourceManager.GetString("ErrorAtLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export as PNG.
        /// </summary>
        public static string ExportAsPng {
            get {
                return ResourceManager.GetString("ExportAsPng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export as _PNG....
        /// </summary>
        public static string ExportAsPngMenu {
            get {
                return ResourceManager.GetString("ExportAsPngMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export as SVG.
        /// </summary>
        public static string ExportAsSvg {
            get {
                return ResourceManager.GetString("ExportAsSvg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export as SV_G....
        /// </summary>
        public static string ExportAsSvgMenu {
            get {
                return ResourceManager.GetString("ExportAsSvgMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulk export as _PNG....
        /// </summary>
        public static string ExportBulkAsPng {
            get {
                return ResourceManager.GetString("ExportBulkAsPng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulk export as _SVG....
        /// </summary>
        public static string ExportBulkAsSvg {
            get {
                return ResourceManager.GetString("ExportBulkAsSvg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more flags could not be exported. Check your syntax and if any custom overlays could not be found..
        /// </summary>
        public static string ExportBulkError {
            get {
                return ResourceManager.GetString("ExportBulkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export completed successfully..
        /// </summary>
        public static string ExportBulkSuccess {
            get {
                return ResourceManager.GetString("ExportBulkSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag.
        /// </summary>
        public static string Flag {
            get {
                return ResourceManager.GetString("Flag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate random flag.
        /// </summary>
        public static string GenerateRandomFlag {
            get {
                return ResourceManager.GetString("GenerateRandomFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid size.
        /// </summary>
        public static string GridSize {
            get {
                return ResourceManager.GetString("GridSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move down.
        /// </summary>
        public static string MoveDown {
            get {
                return ResourceManager.GetString("MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move up.
        /// </summary>
        public static string MoveUp {
            get {
                return ResourceManager.GetString("MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file selected..
        /// </summary>
        public static string NoFile {
            get {
                return ResourceManager.GetString("NoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open....
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new overlay.
        /// </summary>
        public static string OverlayAdd {
            get {
                return ResourceManager.GetString("OverlayAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t load custom overlay &quot;{0}&quot;..
        /// </summary>
        public static string OverlayLoadError {
            get {
                return ResourceManager.GetString("OverlayLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An overlay with the name &quot;{0}&quot; already exists..
        /// </summary>
        public static string OverlayNameExists {
            get {
                return ResourceManager.GetString("OverlayNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlays.
        /// </summary>
        public static string Overlays {
            get {
                return ResourceManager.GetString("Overlays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radius.
        /// </summary>
        public static string Radius {
            get {
                return ResourceManager.GetString("Radius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ratio.
        /// </summary>
        public static string Ratio {
            get {
                return ResourceManager.GetString("Ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must restart in order for the changes to take effect..
        /// </summary>
        public static string RestartForChanges {
            get {
                return ResourceManager.GetString("RestartForChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate?.
        /// </summary>
        public static string Rotate {
            get {
                return ResourceManager.GetString("Rotate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation.
        /// </summary>
        public static string Rotation {
            get {
                return ResourceManager.GetString("Rotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save _as...
        /// </summary>
        public static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes to {0}?.
        /// </summary>
        public static string SaveChangesPrompt {
            get {
                return ResourceManager.GetString("SaveChangesPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save.
        /// </summary>
        public static string SaveMenu {
            get {
                return ResourceManager.GetString("SaveMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shapes.
        /// </summary>
        public static string Shapes {
            get {
                return ResourceManager.GetString("Shapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show grid.
        /// </summary>
        public static string ShowGrid {
            get {
                return ResourceManager.GetString("ShowGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuffle colors.
        /// </summary>
        public static string ShuffleColors {
            get {
                return ResourceManager.GetString("ShuffleColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skew X.
        /// </summary>
        public static string SkewX {
            get {
                return ResourceManager.GetString("SkewX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skew Y.
        /// </summary>
        public static string SkewY {
            get {
                return ResourceManager.GetString("SkewY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special.
        /// </summary>
        public static string Special {
            get {
                return ResourceManager.GetString("Special", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outline.
        /// </summary>
        public static string Stroke {
            get {
                return ResourceManager.GetString("Stroke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rounded?.
        /// </summary>
        public static string StrokeCurved {
            get {
                return ResourceManager.GetString("StrokeCurved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thickness.
        /// </summary>
        public static string Thickness {
            get {
                return ResourceManager.GetString("Thickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle texture.
        /// </summary>
        public static string ToggleTexture {
            get {
                return ResourceManager.GetString("ToggleTexture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle visibility.
        /// </summary>
        public static string ToggleVisibility {
            get {
                return ResourceManager.GetString("ToggleVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled.
        /// </summary>
        public static string Untitled {
            get {
                return ResourceManager.GetString("Untitled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _World flag presets.
        /// </summary>
        public static string WorldFlagPresets {
            get {
                return ResourceManager.GetString("WorldFlagPresets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string X {
            get {
                return ResourceManager.GetString("X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X1.
        /// </summary>
        public static string X1 {
            get {
                return ResourceManager.GetString("X1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X2.
        /// </summary>
        public static string X2 {
            get {
                return ResourceManager.GetString("X2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X3.
        /// </summary>
        public static string X3 {
            get {
                return ResourceManager.GetString("X3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X4.
        /// </summary>
        public static string X4 {
            get {
                return ResourceManager.GetString("X4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        public static string Y {
            get {
                return ResourceManager.GetString("Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y1.
        /// </summary>
        public static string Y1 {
            get {
                return ResourceManager.GetString("Y1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y2.
        /// </summary>
        public static string Y2 {
            get {
                return ResourceManager.GetString("Y2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y3.
        /// </summary>
        public static string Y3 {
            get {
                return ResourceManager.GetString("Y3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y4.
        /// </summary>
        public static string Y4 {
            get {
                return ResourceManager.GetString("Y4", resourceCulture);
            }
        }
    }
}
